version: '3.3'

services:
  wordpress:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./wp-content/plugins:/var/www/html/wp-content/plugins:delegate
    links:
      - mysql
    networks:
      - wptest
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - wptest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wp'
      MYSQL_USER: 'wp'
      MYSQL_PASSWORD: 'wp'
networks:
  wptest:
    external: false