version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    networks:
      - wptest
  mysql:
    restart: always
    image: mysql:5.7
    networks:
      - wptest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wp'
      MYSQL_USER: 'wp'
      MYSQL_PASSWORD: 'wp'
networks:
  wptest:
    external: false