name: Plugin asset/readme update
on:
  push:
    branches:
      - trunk
jobs:
  trunk:
    - name: WordPress Plugin Deploy no version
      id: deploy
      uses: ./.github/actions/wp-assets
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG : 360deg-javascript-viewer
        ASSETS_DIR : plugin-assets