name: Plugin asset/readme update
on:
  push:
    branches:
      - trunk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Single Deploy
        uses: ./.github/actions/wp-assets
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG : 360deg-javascript-viewer
          ASSETS_DIR : plugin-assets