# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Create zip file 
      - name: Create zip file
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./360-jsv.zip ./wp-content/plugins/360-jsv

      # Deploy on Freemius
      - name: Deploy on Freemius
        uses: buttonizer/freemius-deploy@v0.1.0
        with:
          fileName: ./360-jsv.zip
          releaseMode: pending
          version: 1.0.0
          sandbox: true
        env:
          PUBLIC_KEY: ${{ secrets.FREEMIUS_PUBLIC_KEY }}
          DEV_ID: 9358
          SECRET_KEY: ${{ secrets.FREEMIUS_SECRET_KEY }}
          PLUGIN_SLUG: 360-javascriptviewer-premium
          PLUGIN_ID: 6844
 
  
